#!/usr/bin/env bash

source ./config/config.file

REQUIRED='5.4.0'
INSTALLED=$(php -v | egrep -o -m1 '([0-9]{1,}\.[0-9]{1,}\.[0-9]{1,})')
OLDER=$(echo $INSTALLED $REQUIRED | tr " " "\n" | sort -V | head -n 1)

if [ "$REQUIRED" != "$INSTALLED" ] && [ "$OLDER" == "$INSTALLED" ]; then
 echo " PHP version $REQUIRED is required and $INSTALLED is currently installed"
 exit 1
fi

if [ ! -z "$1" ]; then
    PHP_PORT=$1
elif [ -z "$PHP_PORT" ]; then
    PHP_PORT=8000
fi

trap 'kill_php_server' SIGINT
function kill_php_server() {
    ps aux | grep "[p]hp -S localhost:$PHP_PORT -t ./public/" | awk '{print $2}' | xargs -r kill -9
}

LOG_FILE="./logs/$( date +'%Y%m%d' )_$LOG_NAME.log"
touch $LOG_FILE
{ php -S localhost:$PHP_PORT -t ./public/ & tail -f $LOG_FILE; }
